# Generated by Django 4.0.5 on 2022-07-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=30)),
                (
                    'soma_notas_maxima_categorias',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    'media_maxima_sumarios',
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    'pontuacao_geral_maxima_sumarios',
                    models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=20)),
                (
                    'soma_notas_maxima_topicos',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ('max_sumario', models.IntegerField(blank=True, null=True)),
                (
                    'area',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='produto.area',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=20)),
                (
                    'soma_todas_notas_calculadas',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ('media_sumarios', models.IntegerField(blank=True, null=True)),
                (
                    'pontuacao_geral_sumario',
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    'media_normalizada',
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    'pontuacao_geral_normalizada',
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    'area',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='produto.area',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=20)),
                (
                    'peso',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    'nota_maxima',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    'categoria',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='produto.categoria',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Sumario',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'somatorio',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ('sumario', models.IntegerField(blank=True, null=True)),
                (
                    'sumario_normalizacao',
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    'categoria',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='produto.categoria',
                    ),
                ),
                (
                    'produto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='produto.produto',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nota',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    'nota_calculada',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    'produto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='produto.produto',
                    ),
                ),
                (
                    'topico',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='produto.topico',
                    ),
                ),
            ],
        ),
    ]
