# Generated by Django 4.0.5 on 2022-07-01 21:22
from django.db import migrations


def populating(apps, schema_editor):
    # AREA
    Area = apps.get_model('produto', 'Area')
    area_batedeira = Area(nome='Batedeiras')
    area_batedeira.save()

    # PRODUTO
    Produto = apps.get_model('produto', 'Produto')
    produto_bella_massa = Produto(nome='Bella Massa', area=area_batedeira)
    produto_bella_massa.save()

    produto_britania_perola = Produto(
        nome='Britania Perola', area=area_batedeira
    )
    produto_britania_perola.save()

    produto_mallory_giromax = Produto(
        nome='Mallory Giromax', area=area_batedeira
    )
    produto_mallory_giromax.save()

    # CATEGORIA
    Categoria = apps.get_model('produto', 'Categoria')
    categoria_desempenho = Categoria(nome='Desempenho', area=area_batedeira)
    categoria_desempenho.save()

    categoria_design = Categoria(
        nome='Design e Acabamento', area=area_batedeira
    )
    categoria_design.save()

    categoria_praticidade = Categoria(nome='Praticidade', area=area_batedeira)
    categoria_praticidade.save()

    categoria_limpeza = Categoria(nome='Limpeza', area=area_batedeira)
    categoria_limpeza.save()

    categoria_Seguranca = Categoria(nome='Segurança', area=area_batedeira)
    categoria_Seguranca.save()

    categoria_outros = Categoria(nome='Outros Pontos', area=area_batedeira)
    categoria_outros.save()

    # TOPICO
    Topico = apps.get_model('produto', 'Topico')

    topicos_categoria_desempenho = [
        Topico(nome='Velocidades', peso=2.5, categoria=categoria_desempenho),
        Topico(nome='Força', peso=2.0, categoria=categoria_desempenho),
        Topico(
            nome='Tamanho Batedores', peso=1.0, categoria=categoria_desempenho
        ),
        Topico(
            nome='Massas Leve Fixa', peso=1.2, categoria=categoria_desempenho
        ),
        Topico(
            nome='Massas Leve Pression',
            peso=0.8,
            categoria=categoria_desempenho,
        ),
        Topico(
            nome='Massas Pesadas Fixa',
            peso=1.5,
            categoria=categoria_desempenho,
        ),
        Topico(
            nome='Rotação Automática', peso=1.0, categoria=categoria_desempenho
        ),
        Topico(
            nome='Amplitude Sonora', peso=2.5, categoria=categoria_desempenho
        ),
    ]

    topicos_design = [
        Topico(nome='Design de Base', peso=0.5, categoria=categoria_design),
        Topico(
            nome='Design do Corpo+Moto', peso=0.5, categoria=categoria_design
        ),
        Topico(
            nome='Design dos Acessorio', peso=0.5, categoria=categoria_design
        ),
        Topico(
            nome='Design dos Batedores', peso=0.3, categoria=categoria_design
        ),
        Topico(
            nome='Acabamento e Encaixe', peso=2, categoria=categoria_design
        ),
        Topico(nome='Material Escrito', peso=0.8, categoria=categoria_design),
        Topico(nome='Materiais', peso=1, categoria=categoria_design),
    ]

    topicos_praticidade = [
        Topico(
            nome='Utilização Montada', peso=2, categoria=categoria_praticidade
        ),
        Topico(
            nome='Utilização Solta', peso=2, categoria=categoria_praticidade
        ),
        Topico(
            nome='Descancar Modo', peso=0.5, categoria=categoria_praticidade
        ),
        Topico(
            nome='Tamanho Tigelas', peso=1.2, categoria=categoria_praticidade
        ),
        Topico(
            nome='Utilizacao Acessorios',
            peso=1.2,
            categoria=categoria_praticidade,
        ),
        Topico(
            nome='Manuseio e Guardar',
            peso=0.7,
            categoria=categoria_praticidade,
        ),
        Topico(
            nome='Limpeza Diaria', peso=0.6, categoria=categoria_praticidade
        ),
    ]

    topicos_limpeza = [
        Topico(nome='Limpeza Diária', peso=2, categoria=categoria_limpeza),
        Topico(nome='Robustez a Limpeza', peso=1, categoria=categoria_limpeza),
        Topico(
            nome='Locais de Acumulo', peso=1.5, categoria=categoria_limpeza
        ),
        Topico(nome='Materiais', peso=1, categoria=categoria_limpeza),
    ]

    topicos_Seguranca = [
        Topico(nome='Excaixe base', peso=0.7, categoria=categoria_Seguranca),
        Topico(
            nome='Des/Excaixe batedores',
            peso=0.5,
            categoria=categoria_Seguranca,
        ),
        Topico(
            nome='Estabilidade quando levantada',
            peso=1.0,
            categoria=categoria_Seguranca,
        ),
        Topico(
            nome='Carregar o produto', peso=0.7, categoria=categoria_Seguranca
        ),
        Topico(
            nome='Vibração no Manual ou montada',
            peso=1,
            categoria=categoria_Seguranca,
        ),
        Topico(
            nome='Deteção do batedor levantado',
            peso=0.7,
            categoria=categoria_Seguranca,
        ),
        Topico(
            nome='Cabo de Alimentação', peso=0.5, categoria=categoria_Seguranca
        ),
    ]

    topicos_outros = [
        Topico(nome='Manual', peso=0.3, categoria=categoria_outros),
        Topico(nome='Tempo de Garantia', peso=2, categoria=categoria_outros),
        Topico(nome='Robuztez Aparente', peso=3, categoria=categoria_outros),
        Topico(nome='Embalagem', peso=0.5, categoria=categoria_outros),
        Topico(nome='Outros Detalhes', peso=2, categoria=categoria_outros),
    ]

    Topico.objects.bulk_create(topicos_categoria_desempenho)
    Topico.objects.bulk_create(topicos_design)
    Topico.objects.bulk_create(topicos_praticidade)
    Topico.objects.bulk_create(topicos_limpeza)
    Topico.objects.bulk_create(topicos_Seguranca)
    Topico.objects.bulk_create(topicos_outros)

    # Nota
    Nota = apps.get_model('produto', 'Nota')

    notas_categoria_desempenho = [
        Nota(
            produto=produto_bella_massa,
            topico=topicos_categoria_desempenho[0],
            nota=6.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_categoria_desempenho[1],
            nota=6.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_categoria_desempenho[2],
            nota=7.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_categoria_desempenho[3],
            nota=6.5,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_categoria_desempenho[4],
            nota=7.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_categoria_desempenho[5],
            nota=7.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_categoria_desempenho[6],
            nota=3.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_categoria_desempenho[7],
            nota=5.0,
        ),
        ##################################################
        Nota(
            produto=produto_britania_perola,
            topico=topicos_categoria_desempenho[0],
            nota=4.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_categoria_desempenho[1],
            nota=4.5,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_categoria_desempenho[2],
            nota=7.2,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_categoria_desempenho[3],
            nota=6.5,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_categoria_desempenho[4],
            nota=7.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_categoria_desempenho[5],
            nota=7.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_categoria_desempenho[6],
            nota=3.5,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_categoria_desempenho[7],
            nota=5.5,
        ),
        #######################################################
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_categoria_desempenho[0],
            nota=7.5,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_categoria_desempenho[1],
            nota=6.4,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_categoria_desempenho[2],
            nota=5.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_categoria_desempenho[3],
            nota=2.5,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_categoria_desempenho[4],
            nota=7.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_categoria_desempenho[5],
            nota=7.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_categoria_desempenho[6],
            nota=2.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_categoria_desempenho[7],
            nota=7.0,
        ),
    ]

    notas_design = [
        Nota(produto=produto_bella_massa, topico=topicos_design[0], nota=4.0),
        Nota(produto=produto_bella_massa, topico=topicos_design[1], nota=6.0),
        Nota(produto=produto_bella_massa, topico=topicos_design[2], nota=8.0),
        Nota(produto=produto_bella_massa, topico=topicos_design[3], nota=7.0),
        Nota(produto=produto_bella_massa, topico=topicos_design[4], nota=6.0),
        Nota(produto=produto_bella_massa, topico=topicos_design[5], nota=6.5),
        Nota(produto=produto_bella_massa, topico=topicos_design[6], nota=6.5),
        ###
        Nota(
            produto=produto_britania_perola, topico=topicos_design[0], nota=3.8
        ),
        Nota(
            produto=produto_britania_perola, topico=topicos_design[1], nota=5.0
        ),
        Nota(
            produto=produto_britania_perola, topico=topicos_design[2], nota=5.0
        ),
        Nota(
            produto=produto_britania_perola, topico=topicos_design[3], nota=7.0
        ),
        Nota(
            produto=produto_britania_perola, topico=topicos_design[4], nota=4.5
        ),
        Nota(
            produto=produto_britania_perola, topico=topicos_design[5], nota=4.5
        ),
        Nota(
            produto=produto_britania_perola, topico=topicos_design[6], nota=5.0
        ),
        ###
        Nota(
            produto=produto_mallory_giromax, topico=topicos_design[0], nota=4.5
        ),
        Nota(
            produto=produto_mallory_giromax, topico=topicos_design[1], nota=5.0
        ),
        Nota(
            produto=produto_mallory_giromax, topico=topicos_design[2], nota=5.0
        ),
        Nota(
            produto=produto_mallory_giromax, topico=topicos_design[3], nota=5.0
        ),
        Nota(
            produto=produto_mallory_giromax, topico=topicos_design[4], nota=4.5
        ),
        Nota(
            produto=produto_mallory_giromax, topico=topicos_design[5], nota=6.5
        ),
        Nota(
            produto=produto_mallory_giromax, topico=topicos_design[6], nota=5.2
        ),
    ]

    notas_praticidade = [
        Nota(
            produto=produto_bella_massa,
            topico=topicos_praticidade[0],
            nota=7.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_praticidade[1],
            nota=8.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_praticidade[2],
            nota=7.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_praticidade[3],
            nota=8.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_praticidade[4],
            nota=9.0,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_praticidade[5],
            nota=4.5,
        ),
        Nota(
            produto=produto_bella_massa,
            topico=topicos_praticidade[6],
            nota=6.2,
        ),
        ###
        Nota(
            produto=produto_britania_perola,
            topico=topicos_praticidade[0],
            nota=6.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_praticidade[1],
            nota=3.5,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_praticidade[2],
            nota=0.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_praticidade[3],
            nota=7.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_praticidade[4],
            nota=4.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_praticidade[5],
            nota=5.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_praticidade[6],
            nota=5.0,
        ),
        ###
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_praticidade[0],
            nota=3.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_praticidade[1],
            nota=2.5,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_praticidade[2],
            nota=4.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_praticidade[3],
            nota=6.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_praticidade[4],
            nota=4.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_praticidade[5],
            nota=6.5,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_praticidade[6],
            nota=6.5,
        ),
        ###
    ]

    notas_limpeza = [
        Nota(produto=produto_bella_massa, topico=topicos_limpeza[0], nota=6.2),
        Nota(produto=produto_bella_massa, topico=topicos_limpeza[1], nota=6.0),
        Nota(produto=produto_bella_massa, topico=topicos_limpeza[2], nota=5.0),
        Nota(produto=produto_bella_massa, topico=topicos_limpeza[3], nota=6.5),
        ###
        Nota(
            produto=produto_britania_perola,
            topico=topicos_limpeza[0],
            nota=5.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_limpeza[1],
            nota=4.5,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_limpeza[2],
            nota=6.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_limpeza[3],
            nota=5.0,
        ),
        ###
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_limpeza[0],
            nota=6.5,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_limpeza[1],
            nota=4.5,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_limpeza[2],
            nota=4.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_limpeza[3],
            nota=5.5,
        ),
        ###
    ]

    notas_seguranca = [
        Nota(
            produto=produto_bella_massa, topico=topicos_Seguranca[0], nota=5.0
        ),
        Nota(
            produto=produto_bella_massa, topico=topicos_Seguranca[1], nota=4.5
        ),
        Nota(
            produto=produto_bella_massa, topico=topicos_Seguranca[2], nota=5.5
        ),
        Nota(
            produto=produto_bella_massa, topico=topicos_Seguranca[3], nota=5.0
        ),
        Nota(
            produto=produto_bella_massa, topico=topicos_Seguranca[4], nota=5.0
        ),
        Nota(
            produto=produto_bella_massa, topico=topicos_Seguranca[5], nota=0.0
        ),
        Nota(
            produto=produto_bella_massa, topico=topicos_Seguranca[6], nota=6.0
        ),
        ###
        Nota(
            produto=produto_britania_perola,
            topico=topicos_Seguranca[0],
            nota=6.5,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_Seguranca[1],
            nota=5.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_Seguranca[2],
            nota=6.5,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_Seguranca[3],
            nota=2.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_Seguranca[4],
            nota=5.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_Seguranca[5],
            nota=0.0,
        ),
        Nota(
            produto=produto_britania_perola,
            topico=topicos_Seguranca[6],
            nota=6.0,
        ),
        ###
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_Seguranca[0],
            nota=7.5,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_Seguranca[1],
            nota=7.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_Seguranca[2],
            nota=4.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_Seguranca[3],
            nota=5.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_Seguranca[4],
            nota=6.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_Seguranca[5],
            nota=0.0,
        ),
        Nota(
            produto=produto_mallory_giromax,
            topico=topicos_Seguranca[6],
            nota=3.0,
        ),
        ###
    ]

    notas_outros = [
        Nota(produto=produto_bella_massa, topico=topicos_outros[0], nota=6.0),
        Nota(produto=produto_bella_massa, topico=topicos_outros[1], nota=5.0),
        Nota(produto=produto_bella_massa, topico=topicos_outros[2], nota=7.5),
        Nota(produto=produto_bella_massa, topico=topicos_outros[3], nota=6.0),
        Nota(produto=produto_bella_massa, topico=topicos_outros[4], nota=5.5),
        ###
        Nota(
            produto=produto_britania_perola, topico=topicos_outros[0], nota=5.5
        ),
        Nota(
            produto=produto_britania_perola, topico=topicos_outros[1], nota=5.0
        ),
        Nota(
            produto=produto_britania_perola, topico=topicos_outros[2], nota=5.0
        ),
        Nota(
            produto=produto_britania_perola, topico=topicos_outros[3], nota=5.5
        ),
        Nota(
            produto=produto_britania_perola, topico=topicos_outros[4], nota=4.0
        ),
        ###
        Nota(
            produto=produto_mallory_giromax, topico=topicos_outros[0], nota=4.0
        ),
        Nota(
            produto=produto_mallory_giromax, topico=topicos_outros[1], nota=5.0
        ),
        Nota(
            produto=produto_mallory_giromax, topico=topicos_outros[2], nota=7.0
        ),
        Nota(
            produto=produto_mallory_giromax, topico=topicos_outros[3], nota=6.0
        ),
        Nota(
            produto=produto_mallory_giromax, topico=topicos_outros[4], nota=4.0
        ),
        ###
    ]

    Nota.objects.bulk_create(notas_categoria_desempenho)
    Nota.objects.bulk_create(notas_design)
    Nota.objects.bulk_create(notas_praticidade)
    Nota.objects.bulk_create(notas_limpeza)
    Nota.objects.bulk_create(notas_seguranca)
    Nota.objects.bulk_create(notas_outros)


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [migrations.RunPython(populating)]
