# Generated by Django 4.0.5 on 2022-07-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20220701_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='produto.area'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='nota',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='produto.topico'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produto.area'),
        ),
        migrations.AlterField(
            model_name='sumario',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumarios', to='produto.categoria'),
        ),
        migrations.AlterField(
            model_name='sumario',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumarios', to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='produto.categoria'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
