# Generated by Django 4.0.5 on 2022-06-30 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_sumario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumarioNormalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.IntegerField()),
                ('sumario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumario', to='produto.sumario')),
            ],
        ),
    ]
